language: python
python:
#  - "3.5"
  - "3.6"
#  - "2.6"
 # - "2.7"



script:
  - python pytest

env:
  - DJANGO=2.0.1
  - DJANGO_VERSION=2.0.0

before_install:
  - export DJANGO_SETTINGS_MODULE=your_project.settings
  - export PIP_USE_MIRRORS=true

install:
 # - pip install .
  - pip install -q Django==2.0 --quiet
#  - python setup.py -q install


notifications:
    email:
        recipients:
    #      - jachi36@gmail.com
   #       - odeajustin@gmail.com
   #       - waylon@msulaunchpad.org
