language: python
python:
  - "3.5"
  - "3.6"
  - "django"


script:
  - pytest

env:
  - DJANGO_VERSION=1.10.8
  - DJANGO_VERSION=1.11.5

install:
  - pip install .
  - pip install -q Django==$DJANGO_VERSION
  - python setup.py -q install
