language: python
python:
#  - "3.5"
  - "3.6"
# - "2.6"
 # - "2.7"




env:
  - DJANGO=1.11.10
  - DJANGO_VERSION=1.11.10
  

before_install:
  - export DJANGO_SETTINGS_MODULE=your_project.settings
  - export PIP_USE_MIRRORS=true

install:
 # - pip install .
  - pip install -q Django==1.11.10 --quiet
  - pip install -r requirements.txt
  #- pip install -U pytest
#  - python setup.py -q install


notifications:
    email:
        recipients:
    #      - jachi36@gmail.com
   #       - odeajustin@gmail.com
   #       - waylon@msulaunchpad.org
script:
  - manage.py test
