language: python
python:
  - "3.5"
  - "3.6"





env:
  - DJANGO=2.0.0
  - DJANGO_VERSION=2.0.0
  

before_install:
  - export DJANGO_SETTINGS_MODULE=mysite.settings
  - export PIP_USE_MIRRORS=true

install:
 # - pip install .
  - pip install -q Django==2.0.0 --quiet
  - pip install -r requirements.txt
  #- pip install -U pytest
#  - python setup.py -q install


notifications:
    email:
        recipients:
          - jachiike.madubuko@gmail.com
          - odeajustin@gmail.com
          - waylon@msulaunchpad.org
script:
  - python manage.py test