# Generated by Django 2.0 on 2018-05-04 17:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('attorney', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='legal',
            options={'managed': True},
        ),
        migrations.AddField(
            model_name='form',
            name='doc',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                       to='attorney.Document'),
        ),
        migrations.AlterField(
            model_name='piece',
            name='content',
            field=models.CharField(blank=True, db_column='content', max_length=1000, null=True),
        ),
    ]
