# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-19 11:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('attorney', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='firm',
            name='id',
        ),
        migrations.AddField(
            model_name='firm',
            name='firmID',
            field=models.AutoField(db_column='firmID', default='0', max_length=9, primary_key=True, serialize=False,
                                   unique=True),
        ),
        migrations.AlterField(
            model_name='legal',
            name='legalID',
            field=models.AutoField(db_column='legalID', max_length=9, primary_key=True, serialize=False, unique=True),
        ),
    ]
