# Generated by Django 2.0 on 2018-03-31 22:35

import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('attorney', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='client',
            managers=[
                ('people', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='document',
            managers=[
                ('legals', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='form',
            managers=[
                ('legals', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='lawyer',
            managers=[
                ('people', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='piece',
            managers=[
                ('legals', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='buy',
            name='legal',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='attorney.Legal'),
        ),
        migrations.AlterField(
            model_name='buy',
            name='person',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='attorney.Person'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='employed',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='employed_lawyer', to='attorney.Person'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='employer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='employing_firm', to='attorney.Firm'),
        ),
        migrations.AlterField(
            model_name='firm',
            name='firmID',
            field=models.AutoField(db_column='firmID', default=1, max_length=9, primary_key=True, serialize=False,
                                   unique=True),
        ),
        migrations.AlterField(
            model_name='forstate',
            name='legal',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='attorney.Legal'),
        ),
        migrations.AlterField(
            model_name='forstate',
            name='state',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='attorney.State'),
        ),
        migrations.AlterField(
            model_name='instate',
            name='person',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='attorney.Person'),
        ),
        migrations.AlterField(
            model_name='instate',
            name='state',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='attorney.State'),
        ),
        migrations.AlterField(
            model_name='legal',
            name='legalID',
            field=models.AutoField(db_column='legalID', default=1, max_length=9, primary_key=True, serialize=False,
                                   unique=True),
        ),
        migrations.AlterField(
            model_name='own',
            name='legal',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='attorney.Legal'),
        ),
        migrations.AlterField(
            model_name='own',
            name='person',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='attorney.Person'),
        ),
        migrations.AlterField(
            model_name='person',
            name='personID',
            field=models.AutoField(db_column='personID', default=1, max_length=9, primary_key=True, serialize=False,
                                   unique=True),
        ),
        migrations.AlterField(
            model_name='use',
            name='legal',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='attorney.Legal'),
        ),
        migrations.AlterField(
            model_name='use',
            name='person',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='attorney.Person'),
        ),
        migrations.AlterField(
            model_name='view',
            name='legal',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='attorney.Legal'),
        ),
        migrations.AlterField(
            model_name='view',
            name='person',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='attorney.Person'),
        ),
    ]
