# Generated by Django 2.0 on 2018-04-24 07:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('attorney', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='piece',
            name='content',
            field=models.CharField(blank=True, db_column='content', max_length=500, null=True),
        ),
    ]
